HOST: http://www.skypicker.com/

--- Skypicker ---
---
Welcome to the Skypicker API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---
--
Places Resources
The following is a section of resources related to places - countries, cities, airports
--

Govolo external search api

Params:
dateFrom:dd/mm/yyyy
dateTo:dd/mm/yyyy
from:OPO
to:PRG
locale:en

price for flights in routes list is ignored
temp dev url 178.63.80.217:7777
GET /govolo
> Accept: application/json
< 200
< Content-Type: application/json
{
  "data": [
    {
      "price": "172,00",
      "route": [
        {
          "mapIdfrom": "porto",
          "mapIdto": "frankfurt",
          "dTime": "1365048000",
          "latTo": 41.24805,
          "flyTo": "OPO",
          "return": "false",
          "id": null,
          "airline": "LH",
          "lngTo": -8.68139,
          "cityTo": "Porto",
          "cityFrom": "Frankfurt",
          "lngFrom": 8.68213,
          "aTime": "1365061500",
          "flyFrom": "FRA",
          "price": "172,00",
          "latFrom": 50.11092
        },
        {
          "mapIdfrom": "frankfurt",
          "mapIdto": "london",
          "dTime": "1365071100",
          "latTo": 50.11092,
          "flyTo": "FRA",
          "return": "false",
          "id": null,
          "airline": "LH",
          "lngTo": 8.68213,
          "cityTo": "Frankfurt",
          "cityFrom": "London",
          "lngFrom": -0.12768,
          "aTime": "1365073500",
          "flyFrom": "LHR",
          "price": "172,00",
          "latFrom": 51.50734
        },
        {
          "mapIdfrom": "london",
          "mapIdto": "porto",
          "dTime": "1365328200",
          "latTo": 51.50734,
          "flyTo": "LGW",
          "return": "true",
          "id": null,
          "airline": "TP",
          "lngTo": -0.12768,
          "cityTo": "London",
          "cityFrom": "Porto",
          "lngFrom": -8.68139,
          "aTime": "1365336600",
          "flyFrom": "OPO",
          "price": "172,00",
          "latFrom": 41.24805
        }
      ],
      "cityTo": "Porto",
      "cityFrom": "London",
      "dTime": "1365048000",
      "aTime": "1365061500",
      "flyFrom": "LGW",
      "id": "NaeebdOKJKDCNabbibIQw|NaeebdODCNIQCaajagIQw|CahebdVISYKJKaaddbXJw",
      "flyTo": "OPO"
    }]
}
List places from which you can fly.
GET /places
> Accept: application/json
< 200
< Content-Type: application/json
{ "data": [
    { "numberOfAirports": 1, "id": "SI", "parentId": null, "type": 1, "value": "Slovenia" },
    { "numberOfAirports": 1, "id": "LGW", "parentId": "london", "type": 0, "value": "London Gatwick (LGW)" }
], "count": 2
}


List places from which you can fly including GPS coordinates.
GET /places?geo=1
< 200
< Content-Type: application/json
[
    { "numberOfAirports": 1, "id": "SI", "parentId": null, "type": 1, "value": "Slovenia", "lat": 50, "lng":15.432 },
    { "numberOfAirports": 1, "id": "LGW", "parentId": "london", "type": 0, "value": "London Gatwick (LGW)", "lat":49.2323, "lng":18.991 }
]


Get information about particular place.
GET /places/{id}{?geo}
< 200
< Content-Type: application/json
{ "numberOfAirports": 1, "id": "SI", "parentId": null, "type": 1, "value": "Slovenia", "lat": 50.329, "lng": 15.243 }


--
Flights Resources
The following is a section of resources related to flights

Params:
dateFrom:28/11/2012
dateTo:28/12/2012
from:CZ
to:anywhere
locale:en
typeFlight:oneway
onlyWorkingDays:0
onlyWeekends:1
directFlights:0
--
List flights you can book.
GET /flights
> Accept: application/json
< 200
< Content-Type: application/json
{
    "connections" : [
        {
            "id" : "ARN",
            "name" : "Stockholm"
        },
        {
            "id" : "BCN",
            "name" : "Barcelona"
        },
        {
            "id" : "BGY",
            "name" : "Milan"
        }
    ],
    "data" : [
        {
            "aTime" : 1358412600,
            "cityFrom" : "Prague",
            "cityTo" : "Budapest",
            "dTime" : 1358335800,
            "flyFrom" : "PRG",
            "flyTo" : "BUD",
            "id" : "3545416|3742828",
            "price" : 108.43232999999999,
            "taxFee": "15.3",
            "route" : [
                {
                    "airline" : "U2",
                    "aTime" : 1358340900,
                    "cityFrom" : "Prague",
                    "cityTo" : "Milan",
                    "dTime" : 1358335800,
                    "flyFrom" : "PRG",
                    "flyTo" : "MXP",
                    "id" : "3545416",
                    "latFrom" : 50.100830000000002,
                    "latTo" : 45.465449999999997,
                    "lngFrom" : 14.26,
                    "lngTo" : 9.1865199999999998,
                    "mapIdfrom" : "prague",
                    "mapIdto" : "milan",
                    "price" : 62.43,
                    "return" : "false"
                },
                {
                    "airline" : "W6",
                    "aTime" : 1358412600,
                    "cityFrom" : "Milan",
                    "cityTo" : "Budapest",
                    "dTime" : 1358406900,
                    "flyFrom" : "MXP",
                    "flyTo" : "BUD",
                    "id" : "3742828",
                    "latFrom" : 45.465449999999997,
                    "latTo" : 47.436929999999997,
                    "lngFrom" : 9.1865199999999998,
                    "lngTo" : 19.255590000000002,
                    "mapIdfrom" : "milan",
                    "mapIdto" : "budapest",
                    "price" : 17.989999999999998,
                    "return" : "false"
                }
            ]
        },
        {
            "aTime" : 1358413200,
            "cityFrom" : "Brno",
            "cityTo" : "Linz",
            "dTime" : 1358348700,
            "flyFrom" : "BRQ",
            "flyTo" : "LNZ",
            "id" : "3669969|4473768",
            "price" : 98.917330000000007,
            "taxFee": "5.12",
            "route" : [
                {
                    "airline" : "FR",
                    "aTime" : 1358352900,
                    "cityFrom" : "Brno",
                    "cityTo" : "London",
                    "dTime" : 1358348700,
                    "flyFrom" : "BRQ",
                    "flyTo" : "STN",
                    "id" : "3669969",
                    "latFrom" : 49.151269999999997,
                    "latTo" : 51.507339999999999,
                    "lngFrom" : 16.694430000000001,
                    "lngTo" : -0.12767999999999999,
                    "mapIdfrom" : "brno",
                    "mapIdto" : "london",
                    "price" : 59.409999999999997,
                    "return" : "false"
                },
                {
                    "airline" : "FR",
                    "aTime" : 1358413200,
                    "cityFrom" : "London",
                    "cityTo" : "Linz",
                    "dTime" : 1358402400,
                    "flyFrom" : "STN",
                    "flyTo" : "LNZ",
                    "id" : "4473768",
                    "latFrom" : 51.507339999999999,
                    "latTo" : 48.233220000000003,
                    "lngFrom" : -0.12767999999999999,
                    "lngTo" : 14.18751,
                    "mapIdfrom" : "london",
                    "mapIdto" : "linz",
                    "price" : 27.870000000000001,
                    "return" : "false"
                }
            ]
        },
        {
            "aTime" : 1358352900,
            "cityFrom" : "Brno",
            "cityTo" : "London",
            "dTime" : 1358348700,
            "flyFrom" : "BRQ",
            "flyTo" : "STN",
            "id" : "3669969",
            "price" : 67.331329999999994,
            "taxFee": "20.3",
            "route" : [ 
                {
                    "airline" : "FR",
                    "aTime" : 1358352900,
                    "cityFrom" : "Brno",
                    "cityTo" : "London",
                    "dTime" : 1358348700,
                    "flyFrom" : "BRQ",
                    "flyTo" : "STN",
                    "id" : "3669969",
                    "latFrom" : 49.151269999999997,
                    "latTo" : 51.507339999999999,
                    "lngFrom" : 16.694430000000001,
                    "lngTo" : -0.12767999999999999,
                    "mapIdfrom" : "brno",
                    "mapIdto" : "london",
                    "price" : 59.409999999999997,
                    "return" : "false"
                }
            ]
        },
        {
            "aTime" : 1358340900,
            "cityFrom" : "Prague",
            "cityTo" : "Milan",
            "dTime" : 1358335800,
            "flyFrom" : "PRG",
            "flyTo" : "MXP",
            "id" : "3545416",
            "price" : 86.444559999999996,
            "taxFee": "4.77",
            "route" : [
                {
                    "airline" : "U2",
                    "aTime" : 1358340900,
                    "cityFrom" : "Prague",
                    "cityTo" : "Milan",
                    "dTime" : 1358335800,
                    "flyFrom" : "PRG",
                    "flyTo" : "MXP",
                    "id" : "3545416",
                    "latFrom" : 50.100830000000002,
                    "latTo" : 45.465449999999997,
                    "lngFrom" : 14.26,
                    "lngTo" : 9.1865199999999998,
                    "mapIdfrom" : "prague",
                    "mapIdto" : "milan",
                    "price" : 62.43,
                    "return" : "false"
                }
            ]
        },
        {
            "aTime" : 1358541300,
            "cityFrom" : "Brno",
            "cityTo" : "Frankfurt",
            "dTime" : 1358446500,
            "flyFrom" : "BRQ",
            "flyTo" : "HHN",
            "id" : "3669967|3694249",
            "price" : 96.457999999999998,
            "taxFee": "5.23",
            "route" : [
                {
                    "airline" : "FR",
                    "aTime" : 1358450700,
                    "cityFrom" : "Brno",
                    "cityTo" : "London",
                    "dTime" : 1358446500,
                    "flyFrom" : "BRQ",
                    "flyTo" : "STN",
                    "id" : "3669967",
                    "latFrom" : 49.151269999999997,
                    "latTo" : 51.507339999999999,
                    "lngFrom" : 16.694430000000001,
                    "lngTo" : -0.12767999999999999,
                    "mapIdfrom" : "brno",
                    "mapIdto" : "london",
                    "price" : 59.409999999999997,
                    "return" : "false"
                },
                {
                    "airline" : "FR",
                    "aTime" : 1358541300,
                    "cityFrom" : "London",
                    "cityTo" : "Frankfurt",
                    "dTime" : 1358532900,
                    "flyFrom" : "STN",
                    "flyTo" : "HHN",
                    "id" : "3694249",
                    "latFrom" : 51.507339999999999,
                    "latTo" : 50.11092,
                    "lngFrom" : -0.12767999999999999,
                    "lngTo" : 8.6821300000000008,
                    "mapIdfrom" : "london",
                    "mapIdto" : "frankfurt",
                    "price" : 25.699999999999999,
                    "return" : "false"
                }
            ]
        }
    ],
    "time" : 2.98
}


--
Geo Resources
The following is a section of resources related to geolocation.
--
Return default FROM country for user.
GET /geo
> Accept: application/json
< 200
< Content-Type: application/json
{
    "code": "CZ"
}


--
Airlines Resources
The following is a section of resources related to airlines.
--
Return available airlines.
GET /airlines
> Accept: application/json
< 200
< Content-Type: application/json
[
    {
        "id": "FR",
        "name": "Ryanair"
    },
    {
        "id": "U2",
        "name": "easyJet"
    }
]